baseURL = "https://phatngluu.github.io"
languageCode = "en-us"
title = "Luu Nguyen Phat"
publishDir = "docs"
copyright = "Phat Nguyen Luu" # cactus will use title if copyright is not set
canonifyURLs = true # If set true, then whenever Hugo build markdown file, it will add baseURL before the path of image and apply for result html.
# googleAnalytics = "UA-1234-5"


# summaryLength = 2

# Main menu which appears below site header.
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "Categories"
url = "/categories"
weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4

[[menu.main]]
name = "About"
url = "/about"
weight = 5

[[menu.main]]
name = "Admin"
url = "/admin"
weight = 6

[markup]
  [markup.tableOfContents]
    endLevel = 6
    ordered = false
    startLevel = 1

[params]

  colortheme = "dark" # dark, light, white, or classic

  # Home page settings
  mainSection = "posts" # your main section
  showAllPostsOnHomePage = false # default
  postsOnHomePage = 5 # this option will be ignored if showAllPostsOnHomePage is set to true
  tagsOverview = true # show tags overview by default.
  showProjectsList = false # show projects list by default (if projects data file exists).
  projectsUrl = "https://github.com/gohugoio" # title link for projects list

  # https://gohugo.io/functions/format/#hugo-date-and-time-templating-reference
  dateFormat = "2006-01-02" # default

  # Post page settings
  show_updated = false # default

  [params.comments]
    enabled = false # default
    engine = "disqus" # more supported engines will be added.
