# This is a basic workflow to help you get started with Actions

name: Auto-publish

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Step 1 – 
      - name: Change directory
        run: cd /home/runner/work/phatngluu.github.io/phatngluu.github.io/.git/

      # Step 2 - Sets up the latest version of Hugo
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
            hugo-version: 'latest'
      # Step 3 - Git auth
      - name: Git auth
        run: |
          git config user.email "yadsendew@prontonmail.com"
          git config user.name "phatngluu"

      # Step 4 – Runs a single command using the runners shell
      - name: Run script
        run: ./publish.sh
